# Generated by Django 3.0.3 on 2020-02-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='receive_addr',
            new_name='receiver_addr',
        ),
    ]
