# Generated by Django 3.0.3 on 2020-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexCategory',
            new_name='IndexGoodsCategory',
        ),
        migrations.AlterField(
            model_name='indexpromotion',
            name='url',
            field=models.CharField(max_length=256, verbose_name='活动页面链接'),
        ),
    ]
