# Generated by Django 3.0.3 on 2020-03-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='indexslide',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='商品图片'),
        ),
    ]
